# Generated by Django 3.2.4 on 2021-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='roles',
            field=models.ManyToManyField(blank=True, to='portal.StaffRoles'),
        ),
    ]
