# Generated by Django 3.2.4 on 2021-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210720_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(help_text='Stripe ID of customer', max_length=255, unique=True, verbose_name='Stripe Customer ID'),
        ),
    ]
