# Generated by Django 3.2.4 on 2021-07-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_client_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='domain_name',
            field=models.CharField(default='webmastered.cf', help_text="Customer's website domain name.", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
