# Generated by Django 3.2.4 on 2021-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_client_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cloudflare_zone_id',
            field=models.CharField(default='fb4a03fb410de8d2d5a9cca5624ef765', help_text='CF Zone ID of customer', max_length=255, unique=True, verbose_name='Cloudflare Zone ID'),
            preserve_default=False,
        ),
    ]
