# Generated by Django 3.2.4 on 2021-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_client_cloudflare_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='digitalocean_droplet_id',
            field=models.CharField(default='253134625', help_text='DO Droplet ID of customer', max_length=255, unique=True, verbose_name='DigitalOcean Droplet ID'),
            preserve_default=False,
        ),
    ]
