# Generated by Django 3.2.4 on 2021-07-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_client_digitalocean_droplet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifying name for this pricing table.', max_length=255, unique=True)),
                ('html_table', models.TextField(blank=True, help_text='HTML table for pricing.', max_length=500000, verbose_name='HTML Table')),
            ],
            options={
                'verbose_name': 'Pricing Table',
                'verbose_name_plural': 'Pricing Tables',
            },
        ),
    ]
