# Generated by Django 3.2.4 on 2021-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_pricingtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtable',
            name='html_table',
            field=models.TextField(help_text='HTML table for pricing.', max_length=500000, verbose_name='HTML Table'),
        ),
    ]
