# Generated by Django 3.2.4 on 2021-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_pricingtable_html_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtable',
            name='hosting_prices',
            field=models.BooleanField(default=False, help_text='If this is set to true, this table will be displayed in the client portal under the server upgrades page.'),
        ),
    ]
