# Generated by Django 3.2.4 on 2021-07-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_pricingtable_hosting_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_tier', models.CharField(help_text='This is the hosting tier that the client wants to upgrade to.', max_length=255, verbose_name='Requested tier')),
                ('client_comments', models.TextField(help_text='Comments left by client.', max_length=500000, verbose_name='Client comments')),
                ('scheduled_date', models.DateField(blank=True, help_text='Date scheduled to carry out the upgrade.', null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Scheduled time on the scheduled date when the upgrade process will start', null=True)),
                ('is_finished', models.BooleanField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile_upgrades', to='portal.client')),
            ],
            options={
                'verbose_name': 'Hosting Upgrade Request',
                'verbose_name_plural': 'Hosting Upgrade Requests',
            },
        ),
    ]
