# Generated by Django 3.2.4 on 2021-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_hostingupgraderequest_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingupgraderequest',
            name='requested_tier',
            field=models.CharField(choices=[('Professional 18M', 'Professional 18M'), ('Basic 12M', 'Basic 12M'), ('Basic 18M', 'Basic 18M'), ('Professional 12M', 'Professional 12M'), ('Basic 24M', 'Basic 24M'), ('Standard 18M', 'Standard 18M'), ('Professional 24M', 'Professional 24M'), ('Standard 12M', 'Standard 12M'), ('Standard 24M', 'Standard 24M')], help_text='This is the hosting tier that the client wants to upgrade to.', max_length=255, verbose_name='Requested tier'),
        ),
    ]
