# Generated by Django 3.2.4 on 2021-07-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_hostingupgraderequest_requested_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingupgraderequest',
            name='client_comments',
            field=models.TextField(blank=True, help_text='Comments left by client.', max_length=500000, null=True, verbose_name='Client comments'),
        ),
    ]
