# Generated by Django 3.2.4 on 2021-07-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_hostingupgraderequest_client_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingupgraderequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.client'),
        ),
    ]
