# Generated by Django 3.2.4 on 2021-07-30 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_hostingupgraderequest_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostingupgraderequest',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.client'),
        ),
    ]
