# Generated by Django 3.2.4 on 2021-07-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_alter_hostingupgraderequest_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(choices=[('A', 'A Record'), ('AAAA', 'AAAA Record'), ('CNAME', 'CNAME Record'), ('MX', 'MX Record'), ('TXT', 'TXT Record')], help_text='Choose the type of records this is.', max_length=255, verbose_name='Type')),
                ('hostname', models.CharField(help_text='This is the hostname for the records.', max_length=255, verbose_name='Hostname')),
                ('content', models.CharField(help_text='This is where the hostname points to.', max_length=2048, verbose_name='Content')),
                ('ttl', models.IntegerField(blank=True, help_text='OPTIONAL. This is the TTL of the records, this can be left blank.', null=True, verbose_name='TTL')),
                ('priority', models.IntegerField(blank=True, help_text='ONLY FOR MX RECORDS. This is the priority of the record.', null=True, verbose_name='MX Priority')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.client')),
            ],
            options={
                'verbose_name': 'DNS Record Request',
                'verbose_name_plural': 'DNS Record Requests',
            },
        ),
    ]
