# Generated by Django 3.2.4 on 2021-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_dnsrecordrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecordrequest',
            name='added_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnsrecordrequest',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
