# Generated by Django 3.2.4 on 2021-07-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20210731_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrecordrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
