# Generated by Django 3.2.4 on 2021-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_alter_dnsrecordrequest_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnsrecordrequest',
            old_name='is_added',
            new_name='added',
        ),
        migrations.RenameField(
            model_name='dnsrecordrequest',
            old_name='added_datetime',
            new_name='added_timestamp',
        ),
        migrations.AlterField(
            model_name='dnsrecordrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
