# Generated by Django 3.2.4 on 2021-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_alter_dnsrecordrequest_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsrecordrequest',
            name='record',
            field=models.CharField(choices=[('A', 'A Record'), ('AAAA', 'AAAA Record'), ('CNAME', 'CNAME Record'), ('MX', 'MX Record'), ('TXT', 'TXT Record')], help_text='Choose the type of records this is.', max_length=255, verbose_name='Type'),
        ),
    ]
