# Generated by Django 3.2.4 on 2021-08-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_alter_dnsrecordrequest_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(max_length=100000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.client')),
            ],
            options={
                'verbose_name': 'Feature Request',
                'verbose_name_plural': 'Feature Requests',
            },
        ),
    ]
