# Generated by Django 3.2.4 on 2021-08-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_featurerequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequests',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
