# Generated by Django 3.2.4 on 2021-08-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_alter_featurerequests_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioritySupportSubmissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.client')),
            ],
            options={
                'verbose_name': 'Priority Support Submission',
                'verbose_name_plural': 'Priority Support Submissions',
            },
        ),
    ]
