version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./engine:/engine
    command: >
      sh -c "python manage.py migrate && gunicorn engine.wsgi:application --bind 0.0.0.0:8000 --workers=2 --threads=2"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - "5432:5432"