# Generated by Django 3.2.4 on 2021-08-03 10:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', wagtail_color_panel.fields.ColorField(default='#0d6efd', help_text='default is #0d6efd', max_length=7)),
                ('secondary', wagtail_color_panel.fields.ColorField(default='#6c757d', help_text='default is #6c757d', max_length=7)),
                ('success', wagtail_color_panel.fields.ColorField(default='#198754', help_text='default is #198754', max_length=7)),
                ('info', wagtail_color_panel.fields.ColorField(default='#0dcaf0', help_text='default is #0dcaf0', max_length=7)),
                ('warning', wagtail_color_panel.fields.ColorField(default='#ffc107', help_text='default is #ffc107', max_length=7)),
                ('danger', wagtail_color_panel.fields.ColorField(default='#dc3545', help_text='default is #dc3545', max_length=7)),
                ('light', wagtail_color_panel.fields.ColorField(default='#f8f9fa', help_text='default is #f8f9fa', max_length=7)),
                ('dark', wagtail_color_panel.fields.ColorField(default='#212529', help_text='default is #212529', max_length=7)),
                ('tracking_id', models.CharField(blank=True, help_text='Enter your Google Analytics Tracking ID here, it should look something like this: UA-000000-2', max_length=24, null=True, verbose_name='Tracking ID')),
                ('logo', models.ForeignKey(blank=True, help_text='Choose an image for the site logo. This logo will be displayed at various places around the website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_icon', models.ForeignKey(blank=True, help_text='Site icons are what you see in browser tabs and bookmark bars, please upload a square image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Engine Metrics',
            },
        ),
        migrations.CreateModel(
            name='AboutEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'About Engine',
            },
        ),
    ]
