# Generated by Django 3.2.4 on 2021-07-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'Website Settings'},
        ),
    ]
