# Generated by Django 3.2.3 on 2021-06-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('dashboard', '0002_websitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Choose an image for the site logo. This logo will be displayed at various places around the website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='site_icon',
            field=models.ForeignKey(blank=True, help_text='Site icons are what you see in browser tabs and bookmark bars, please upload a square image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
