# Generated by Django 3.2.3 on 2021-06-04 18:42

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210604_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='danger',
            field=wagtail_color_panel.fields.ColorField(default='#dc3545', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='dark',
            field=wagtail_color_panel.fields.ColorField(default='#212529', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='info',
            field=wagtail_color_panel.fields.ColorField(default='#0dcaf0', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='light',
            field=wagtail_color_panel.fields.ColorField(default='#f8f9fa', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='primary',
            field=wagtail_color_panel.fields.ColorField(default='#0d6efd', help_text='default = #0d6efd', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='secondary',
            field=wagtail_color_panel.fields.ColorField(default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='success',
            field=wagtail_color_panel.fields.ColorField(default='#198754', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='warning',
            field=wagtail_color_panel.fields.ColorField(default='#ffc107', max_length=7),
        ),
    ]
