# Generated by Django 3.2.4 on 2021-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210604_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='Enter your Google Analytics Tracking ID here, it should look something like this: UA-000000-2', max_length=24, null=True),
        ),
    ]
