# Generated by Django 3.2.4 on 2021-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_websitesettings_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='tracking_id',
            field=models.CharField(blank=True, help_text='Enter your Google Analytics Tracking ID here, it should look something like this: UA-000000-2', max_length=24, null=True, verbose_name='Tracking ID'),
        ),
    ]
