# Generated by Django 3.2.4 on 2021-06-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_metrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={'verbose_name': 'Engine Metrics'},
        ),
    ]
