# Generated by Django 3.2.4 on 2021-07-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
