# Generated by Django 3.2.4 on 2021-06-18 18:49

import blocks.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading_blocks', wagtail.core.fields.StreamField([('heading_title', blocks.fields.HeadingTitleBlock()), ('heading_subtitle', blocks.fields.HeadingSubtitleBlock()), ('heading_featured_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add a featured image.', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Displays this alternate text if the image cannot be displayed.', required=False)), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], help_text='Add an image caption.', required=False)), ('caption_align', wagtail.core.blocks.ChoiceBlock(choices=[('text-start', 'Left'), ('text-center', 'Centre'), ('text-end', 'Right')], label='Align the caption text.', required=False))]))], blank=True, help_text='Choose blocks to be shown at the top of the page.', null=True)),
                ('body_blocks', wagtail.core.fields.StreamField([('body_title', blocks.fields.BodyTitleBlock()), ('body_paragraph', blocks.fields.BodyParagraphBlock()), ('body_wide_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add an image.', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(default='This is an image.', help_text='Displays this alternate text if the image cannot be displayed.', required=False)), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], help_text='Add an image caption.', required=False)), ('caption_align', wagtail.core.blocks.ChoiceBlock(choices=[('text-start', 'Left'), ('text-center', 'Centre'), ('text-end', 'Right')], label='Align the caption text.', required=False))])), ('body_image_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add an image.', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(default='This is an image.', help_text='Displays this alternate text if the image cannot be displayed.', required=False)), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], help_text='Add an image caption.', required=False)), ('text', blocks.fields.BodyParagraphBlock(help_text='Add some text to display beside the image.', required=True)), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('image-left', 'Image - Text'), ('image-right', 'Text - Image')], label='Align the image and text.', required=False))]))], blank=True, help_text='Choose blocks to be shown in the body.', null=True)),
            ],
            options={
                'verbose_name': 'Blog Listing Page',
                'verbose_name_plural': 'Blog Listing Pages',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading_blocks', wagtail.core.fields.StreamField([('heading_title', blocks.fields.HeadingTitleBlock()), ('heading_subtitle', blocks.fields.HeadingSubtitleBlock()), ('heading_featured_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add a featured image.', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Displays this alternate text if the image cannot be displayed.', required=False)), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], help_text='Add an image caption.', required=False)), ('caption_align', wagtail.core.blocks.ChoiceBlock(choices=[('text-start', 'Left'), ('text-center', 'Centre'), ('text-end', 'Right')], label='Align the caption text.', required=False))]))], blank=True, help_text='Choose blocks to be shown at the top of the page.', null=True)),
                ('body_blocks', wagtail.core.fields.StreamField([('body_title', blocks.fields.BodyTitleBlock()), ('body_paragraph', blocks.fields.BodyParagraphBlock()), ('body_wide_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add an image.', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(default='This is an image.', help_text='Displays this alternate text if the image cannot be displayed.', required=False)), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], help_text='Add an image caption.', required=False)), ('caption_align', wagtail.core.blocks.ChoiceBlock(choices=[('text-start', 'Left'), ('text-center', 'Centre'), ('text-end', 'Right')], label='Align the caption text.', required=False))])), ('body_image_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add an image.', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(default='This is an image.', help_text='Displays this alternate text if the image cannot be displayed.', required=False)), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], help_text='Add an image caption.', required=False)), ('text', blocks.fields.BodyParagraphBlock(help_text='Add some text to display beside the image.', required=True)), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('image-left', 'Image - Text'), ('image-right', 'Text - Image')], label='Align the image and text.', required=False))]))], blank=True, help_text='Choose blocks to be shown in the body.', null=True)),
                ('enable_comments', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Page',
                'verbose_name_plural': 'Blog Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
