# Generated by Django 3.2.4 on 2021-06-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpostcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcomment',
            options={'verbose_name': 'Blog Post Comment', 'verbose_name_plural': 'Blog Post Comments'},
        ),
    ]
