# Generated by Django 3.2.4 on 2021-06-20 14:15

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpostcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_comments', to='blog.blogpostpage'),
        ),
    ]
