# Generated by Django 3.2.4 on 2021-06-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
        ('blog', '0010_alter_blogpostcomment_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostComment',
        ),
    ]
