# Generated by Django 3.2.4 on 2021-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcategory',
            name='name',
            field=models.CharField(help_text='Name your category.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpostcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A slug to identify posts by this category.', max_length=255, unique=True),
        ),
    ]
