# Generated by Django 3.2.3 on 2021-05-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210528_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='heading_streamfields',
            new_name='heading_blocks',
        ),
    ]
