# Generated by Django 3.2.3 on 2021-05-28 19:52

import blocks.fields
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_heading_streamfields_homepage_heading_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='heading_blocks',
            field=wagtail.core.fields.StreamField([('heading_title', blocks.fields.HeadingTitleBlock()), ('heading_subtitle', blocks.fields.HeadingTitleBlock())], blank=True, help_text='Choose blocks to be shown at the top of the page.', null=True),
        ),
    ]
