# Generated by Django 3.2.3 on 2021-05-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_heading_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='page_title',
        ),
    ]
