# Generated by Django 3.2.3 on 2021-06-02 10:39

import blocks.fields
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_body_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body_blocks',
            field=wagtail.core.fields.StreamField([('body_title', blocks.fields.BodyTitleBlock()), ('body_paragraph', blocks.fields.BodyParagraphBlock())], blank=True, help_text='Choose blocks to be shown in the body.', null=True),
        ),
    ]
