# Generated by Django 3.2.3 on 2021-05-29 11:04

import blocks.fields
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='heading_blocks',
            field=wagtail.core.fields.StreamField([('heading_title', blocks.fields.HeadingTitleBlock()), ('heading_subtitle', blocks.fields.HeadingSubtitleBlock()), ('wide_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add an image.', required=True)), ('alt_text', wagtail.core.blocks.CharBlock(help_text='Displays this alternate text if the image cannot be displayed.', required=False)), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'superscript', 'subscript', 'strikethrough'], help_text='Add an image caption.', required=False)), ('caption_align', wagtail.core.blocks.ChoiceBlock(choices=[('text-start', 'Left'), ('text-center', 'Centre'), ('text-end', 'Right')], label='Align the caption text.', required=False))]))], blank=True, help_text='Choose blocks to be shown at the top of the page.', null=True),
        ),
    ]
